<?php

namespace MetaTagEditor\Interfaces;

//This interface contains HTML code constants
interface Html{
    const MAIN_MENU = <<<HTML
<div class="mte_menu_container">
    <div class="mte_menu_header">
        <h1 class="text-center">Editor dei meta tag</h1>
    </div>
    <div class="ms-3 mte_menu_content mt-4">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 col-sm-4 text-center text-sm-start mb-2">
                    <input type="number" id="mte_page_id_get" name="page_id_get" placeholder="ID della pagina">
                </div>
                <div class="col-12 col-sm-4 text-center text-sm-end mb-2">
                    <button id="mte_btn_show" class="btn btn-primary">MOSTRA</button>
                </div>
                <!-- display spinner while waiting meta information of page -->
                <div class="col-12 col-sm-2 d-flex justify-content-center">
                    <div id="mte_page_value_spinner" class="spinner-border d-none" role="status">
                    </div>
                </div>
            </div>
            <div class="row">
                <!-- This div contains label HTML generated by javascript of the article searched  -->
                <div id="mte_page_values" class="mte_labels col-12 mt-3 mb-3">
                </div>
            </div>
            <div class="row">
                <div class="col-12 col-sm-4 text-center text-sm-start mt-4 mb-2">
                    <input type="number" id="mte_page_id_set" name="page_id_set" placeholder="ID della pagina da modificare">
                </div>
                <div class="col-12 col-sm-4 text-center text-sm-end mt-4 mb-2">
                    <button id="mte_btn_edit" class="btn btn-secondary">MODIFICA</button>
                </div>
                <div class="col-12 col-sm-2 d-flex justify-content-center mt-4 mb-2">
                    <div id="mte_page_edit_spinner" class="spinner-border d-none" role="status">
                    </div>
                </div>
            </div>
            <div class="row">
                <!-- Contains input fields to edit meta tags -->
                <div class="mte_data col-12">
                    <div class="row">
                        <div class="col-12 text-start m-2">
                            <label for="mte_canonical_url_edit">URL canonico</label> 
                        </div>
                        <div class="col-12 text-start ms-2 mt-0">
                            <input class="w-75" type="text" id="mte_canonical_url_edit">
                        </div>
                        <div class="col-12 text-start m-2">
                            <label for="mte_title_edit">Titolo</label>
                        </div>
                        <div class="col-12 text-start ms-2 mt-0">
                            <input class="w-75" type="text" id="mte_title_edit">
                        </div>
                        <div class="col-12 text-start m-2">
                            <label for="mte_meta_description_edit">Meta description</label>
                        </div>
                        <div class="col-12 text-start ms-2 mt-0">
                            <input class="w-75" type="text" id="mte_meta_description_edit">
                        </div>
                        <div class="col-12 text-start m-2">
                            <label for="mte_robots_edit">Direttive Robots</label>
                        </div>
                        <div class="col-12 text-start ms-2 mt-0">
                            <div>
                                <input class="mr-2" type="checkbox" id="mte_cb_noindex" name="noindex">
                                <label for="mte_cb_noindex">noindex</label>
                            </div>
                            <div>
                                <input class="mr-2" type="checkbox" id="mte_cb_noindex" name="noindex">
                                <label for="mte_cb_noindex">noindex</label>
                            </div>
                            <div>
                                <input class="mr-2" type="checkbox" id="mte_cb_noindex" name="noindex">
                                <label for="mte_cb_noindex">noindex</label>
                            </div>
                            <div>
                                <input class="mr-2" type="checkbox" id="mte_cb_noindex" name="noindex">
                                <label for="mte_cb_noindex">noindex</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Contain input field to delete custom meta page value -->
            <div id="mte_pagelist_collections" class="row">
                <!-- <div class="col-12 col-sm-4 text-center text-sm-start mt-4 mb-2">
                    <input type="number" id="mte_page_id_delete" name="page_id_delete" placeholder="ID della pagina da cancellare">
                </div>
                <div class="col-12 col-sm-4 text-center text-sm-end mt-4 mb-2">
                    <button id="mte_btn_delete" class="btn btn-danger">ELIMINA</button>
                </div>
                 display spinner while waiting meta information of page --> 
                <div class="col-12 col-sm-2 d-flex justify-content-center mt-4">
                    <div id="mte_page_delete_spinner" class="spinner-border d-none" role="status">
                    </div>
                </div>
            </div> <!-- <div class="row"> -->
        </div>
    </div> <!-- <div class="ms-3 mte_menu_content mt-2"> -->
</div>
HTML;
}
?>