<?php

namespace MetaTagEditor\Interfaces;

//This interface contains HTML code constants
interface Html{
    const MAIN_MENU = <<<HTML
<div class="mte_menu_container">
    <div class="mte_menu_header">
        <h1 class="text-center">Editor dei meta tag</h1>
    </div>
    <div class="ms-3 mte_menu_content mt-4">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 col-sm-4 text-center text-sm-start mb-2">
                    <input type="number" id="mte_page_id_get" name="page_id_get" placeholder="ID della pagina">
                </div>
                <div class="col-12 col-sm-4 text-center text-sm-end mb-2">
                    <button id="mte_btn_show" class="btn btn-primary">MOSTRA</button>
                </div>
                <!-- display spinner while waiting meta information of page -->
                <div class="col-12 col-sm-2 d-flex justify-content-center">
                    <div id="mte_page_value_spinner" class="spinner-border d-none" role="status">
                    </div>
                </div>
            </div>
            <div class="row">
                <!-- This div contains label HTML generated by javascript of the article searched  -->
                <div id="mte_page_values" class="mte_labels col-12 mt-3 mb-3">
                </div>
            </div>
            <div class="row">
                <div class="col-12 col-sm-4 text-center text-sm-start mt-4 mb-2">
                    <input type="number" id="mte_page_id_set" name="page_id_set" placeholder="ID della pagina da modificare">
                </div>
                <div class="col-12 col-sm-4 text-center text-sm-end mt-4 mb-2">
                    <button id="mte_btn_edit" class="btn btn-secondary">MODIFICA</button>
                </div>
                <div class="col-12 col-sm-2 d-flex justify-content-center mt-4 mb-2">
                    <div id="mte_page_edit_spinner" class="spinner-border d-none" role="status">
                    </div>
                </div>
            </div>
            <div class="row">
                <!-- Contains input fields to edit meta tags -->
                <div class="mte_data col-12">
                    <div class="row">
                        <div class="col-12 text-start m-2">
                            <label for="mte_canonical_url_edit">URL canonico</label> 
                        </div>
                        <div class="col-12 text-start ms-2 mt-0">
                            <input class="w-75" type="text" id="mte_canonical_url_edit">
                        </div>
                        <div class="col-12 text-start m-2">
                            <label for="mte_title_edit">Titolo</label>
                        </div>
                        <div class="col-12 text-start ms-2 mt-0">
                            <input class="w-75" type="text" id="mte_title_edit">
                        </div>
                        <div class="col-12 text-start m-2">
                            <label for="mte_meta_description_edit">Meta description</label>
                        </div>
                        <div class="col-12 text-start ms-2 mt-0">
                            <input class="w-75" type="text" id="mte_meta_description_edit">
                        </div>
                        <div class="col-12 text-start m-2">
                            <div class="mte_bold">Direttive robots</div>
                            <div>
                                <input class="mr-2" type="checkbox" id="mte_cb_noindex" name="noindex">
                                <label class="mte_nobold" for="mte_cb_noindex">noindex</label>
                            </div>
                            <div>
                                <input class="mr-2" type="checkbox" id="mte_cb_nofollow" name="nofollow">
                                <label class="mte_nobold" for="mte_cb_nofollow">nofollow</label>
                            </div>
                            <div>
                                <input class="mr-2" type="checkbox" id="mte_cb_noarchive" name="noarchive">
                                <label class="mte_nobold" for="mte_cb_noarchive">noarchive</label>
                            </div>
                            <div>
                                <input class="mr-2" type="checkbox" id="mte_cb_nosnippet" name="nosnippet">
                                <label class="mte_nobold" for="mte_cb_nosnippet">nosnippet</label>
                            </div>
                            <div>
                                <input class="mr-2" type="checkbox" id="mte_cb_indexifembedded" name="indexifembedded">
                                <label class="mte_nobold" for="mte_cb_indexifembedded">indexifembedded</label>
                            </div>
                            <div class="row mt-2">
                                <div class="col-12 col-sm-6">
                                    <label class="mte_nobold" class="mr-2" for="mte_maxsnippet">max-snippet</label>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <input type="number" id="mte_maxsnippet" name="maxsnippet" value="-1">
                                </div>
                            </div>
                            <div class="row mt-2">
                                <div class="col-12 col-sm-6">
                                    <label class="mte_nobold" for="mte_sel_maximagepreview">max-image-preview</label>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <select id="mte_sel_maximagepreview" class="form-select form-select-sm" name="maximagepreview">
                                        <option value="none">none</option>
                                        <option value="standard" selected>standard</option>
                                        <option value="large">large</option>
                                    </select>
                                </div>
                            </div>
                            <div class="row mt-2">
                                <div class="col-12 col-sm-6">
                                    <label class="mte_nobold" class="mr-2" for="mte_maxvideopreview">max-video-preview</label>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <input type="number" id="mte_maxvideopreview" name="maxvideopreview" value="-1">
                                </div>
                            </div>
                            <div>
                                <input class="mr-2" type="checkbox" id="mte_cb_notranslate" name="notranslate">
                                <label class="mte_nobold" for="mte_cb_notranslate">notranslate</label>
                            </div>
                            <div>
                                <input class="mr-2" type="checkbox" id="mte_cb_noimageindex" name="noimageindex">
                                <label class="mte_nobold" for="mte_cb_noimageindex">noimageindex</label>
                            </div>
                            <div class="row mt-2">
                                <div class="col-12 col-sm-6">
                                    <input class="mr-2" type="checkbox" id="mte_cb_unavailableafter" name="unavailableafter">
                                    <label class="mte_nobold" for="mte_cb_unavailableafter">unavailable_after</label>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <input type="datetime-local" id="mte_unavailableafter" name="unavailableafter">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Contain input field to delete custom meta page value -->
            <div id="mte_pagelist_collections" class="row mt-4">
                <!-- <div class="col-12 col-sm-4 text-center text-sm-start mt-4 mb-2">
                    <input type="number" id="mte_page_id_delete" name="page_id_delete" placeholder="ID della pagina da cancellare">
                </div>
                <div class="col-12 col-sm-4 text-center text-sm-end mt-4 mb-2">
                    <button id="mte_btn_delete" class="btn btn-danger">ELIMINA</button>
                </div>
                 display spinner while waiting meta information of page --> 
                <div class="col-12 col-sm-2 d-flex justify-content-center mt-4">
                    <div id="mte_page_delete_spinner" class="spinner-border d-none" role="status">
                    </div>
                </div>
            </div> <!-- <div class="row"> -->
        </div>
    </div> <!-- <div class="ms-3 mte_menu_content mt-2"> -->
</div>
HTML;
}
?>