<?php

namespace MetaTagEditor\Interfaces;

//This interface contains HTML code constants
interface Html{
    const MAIN_MENU = <<<HTML
<div class="mte_menu_container">
    <div class="mte_menu_header">
        <h1 class="text-center">Editor dei meta tag</h1>
    </div>
    <div class="ms-3 mte_menu_content mt-4">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 col-sm-4 text-center text-sm-start mb-2">
                    <input type="number" id="mte_page_id_get" name="page_id_get" placeholder="ID della pagina">
                </div>
                <div class="col-12 col-sm-4 text-center text-sm-end mb-2">
                    <button id="mte_btn_show" class="btn btn-primary">MOSTRA</button>
                </div>
                <!-- display spinner while waiting meta information of page -->
                <div class="col-12 col-sm-2 d-flex justify-content-center">
                    <div id="mte_page_value_spinner" class="spinner-border d-none" role="status">
                    </div>
                </div>
            </div>
            <div class="row">
                <!-- This div contains label HTML generated by javascript of the article searched  -->
                <div id="mte_page_values" class="mte_labels col-12 mt-3 mb-3">
                </div>
            </div>
            <div class="row">
                <div class="col-12 col-sm-4 text-center text-sm-start mb-2">
                    <input type="number" id="mte_page_id_set" name="page_id_set" placeholder="ID della pagina da modificare">
                </div>
                <div class="col-12 col-sm-4 text-center text-sm-end mb-2">
                    <button id="mte_btn_edit" class="btn btn-primary">MODIFICA</button>
                </div>
                <div class="col-12 col-sm-2 d-flex justify-content-center">
                    <div id="mte_page_edit_spinner" class="spinner-border d-none" role="status">
                    </div>
                </div>
            </div>
            <div class="row">
                <!-- Contains input fields to edit meta tags -->
                <div class="mte_data col-12">
                    <div class="row">
                        <div class="col-12 col-md-5 m-2">
                            <label for="mte_canonical_url_edit">URL canonico</label> 
                        </div>
                        <div class="col-12 offset-md-1 col-md-5 m-2">
                            <input type="text" id="mte_canonical_url_edit">
                        </div>
                        <div class="col-12 col-md-5 m-2">
                            <label for="mte_title_edit">Titolo</label>
                        </div>
                        <div class="col-12 offset-md-1 col-md-5 m-2">
                            <input type="text" id="mte_title_edit">
                        </div>
                        <div class="col-12 col-md-5 m-2">
                            <label for="mte_meta_description_edit">Meta description</label>
                        </div>
                        <div class="col-12 offset-md-1 col-md-5 m-2">
                            <input type="text" id="mte_meta_description_edit">
                        </div>
                        <div class="col-12 col-md-5 m-2">
                            <label for="mte_robots_edit">Robots</label>
                        </div>
                        <div class="col-12 offset-md-1 col-md-5 m-2">
                            <input type="text" id="mte_robots_edit">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- <div class="ms-3 mte_menu_content mt-2"> -->
</div>
HTML;
}
?>